spring.application.name=sreagent



# Local WSL testing route via port-forward
ca.sign.url=https://localhost:9000/1.0/sign

# (Later, when deploying the agent inside K8s, we will inject: 
# ca.sign.url=https://step-ca.sre-system.svc.cluster.local:9000/1.0/sign)
